/*
	This file is part of Regressor.

    Regressor is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Regressor is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Regressor.  If not, see <https://www.gnu.org/licenses/>
*/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

void cleanBuffer(char* buffer, int bufferSize);
long double pow2(long double a, int e);

/*
* This program is use to calculate models generated with Regressor128.
* 
* This program do not receives arguments, but, it considers that there
* are two files in the same folder.
*
* The first file is binary_coeficients128.bin; file generated by Regressor128
*
* The second file is inputs.txt; a text file containing the input values used
* to calculate the model. In this file, values must be separated by ","
*/

int main(int argc, char* argv[]){
	
	/*
	* Retrieving data from binary file.
	*/
	FILE* file = fopen("binary_coeficients128.bin","rb");
	
	if(file == NULL){
		printf("can not find binary_coeficient128.bin");
		exit(-1);
	}
	
	int variables = 0;
	int degree = 0;
	int columns = 0;
	
	fread(&variables, sizeof(int), 1, file);
	fread(&degree, sizeof(int), 1, file);
	
	columns = pow(degree+1,variables);
	
	long double* B = (long double*)malloc(sizeof(long double) * columns);
	
	fread(B, sizeof(long double) , columns, file);
	
	fclose(file);
	
	//coeficients array
	long double *varArray = (long double*)malloc(sizeof(long double) * variables);
	char curr = ' ';
	
	char buff[20];
	
	/*
	* Retrieving data from input file
	*/
	
	file = fopen("inputs.txt" , "r");
	
	if(file == NULL){
		printf("can not find inputs.txt");
		exit(-1);
	}
	
	for (int i = 0; i < variables; i++){
		
		cleanBuffer(buff, 20);
		
		int j = 0;
		
		do{
			
			curr = getc(file);
			
			if(curr == ',' || curr == '\n' || curr == EOF){
				++j;
				break;
			}
			
			if(curr == ' '){
				++j;
				continue;
			}
			
			buff[j++] = curr;
			
		}while(1);
		
		double value  = 0.0;
		
		sscanf(buff, "%lf", &value);
		
		*(varArray + i) = (long double)value;
		
	}
	
	fclose(file);
	
	/*
	* Calculating the model response.
	*/
	
	long double _result = *B;
	
	for(int j = 1; j < columns; j++){
            long double product = 1.0;
            
             /*
            * By using limit variable, it's possible to decrease the complexity of building
			* M. As the value of M_i,j = prod{X_i,k} com k < ln(j)/ln(degree+1). 
            */
            int limit = (int)(log(j)/log(degree+1))+1;

            for (int k = 0; k < limit; k++)
            {
                product *= pow2( *(varArray + k) , (((int)((j) / (pow(degree + 1, k)))) % (degree + 1)));
            }

            _result += (product * *(B + j));
        }
	
	printf("model degree: %d \n", degree);
	printf("number of variables: %d \n", variables);
	printf("input values:\n");
	
	for(int i = 0; i < variables; i++){
		printf("--A%d: %lf\n", (i+1), (double) *(varArray + i));
	}
	
	printf("the model response is: %lf", (double) _result);
	
}

/*
* function used to clear residues from char buffer
*/
void cleanBuffer(char* buffer, int bufferSize){
	
	for(int i = 0; i < bufferSize; i++){
		
		buffer[i] = 0;
		
	}
}

/*
* This funcion is a simple implementation of power funcion
* with long double  precision.
*/
long double pow2(long double a, int e){
	long double product = 1;
	for(int i = 0; i < e; i++){
		product *= a;
	}
	
	return product;
}
